iw612-wifi: imx93-var-som: add argument to perform in-band-reset
The driver supports the following options to perform a reset and reload
the firmware:

  # echo "fw_reload=1" > /proc/mwlan/adapterX/config   trigger SDIO inband firmware reset and reload firmware
  # echo "fw_reload=2" > /proc/mwlan/adapterX/config   trigger firmware reload
  # echo "fw_reload=3" > /proc/mwlan/adapterX/config   set firmware reload flag in driver.

For more information, see: https://github.com/nxp-imx/mwifiex/blob/lf-6.1.22_2.0.0/mxm_wifiex/wlan_src/README#L913

Signed-off-by: Nate Drude <nate.d@variscite.com>

diff --git a/recipes-connectivity/iw612-utils/iw612-utils/imx93-var-som/iw612-wifi b/recipes-connectivity/iw612-utils/iw612-utils/imx93-var-som/iw612-wifi
--- a/recipes-connectivity/iw612-utils/iw612-utils/imx93-var-som/iw612-wifi
+++ b/recipes-connectivity/iw612-utils/iw612-utils/imx93-var-som/iw612-wifi
@@ -28,6 +28,17 @@ wifi_stop()
 	modprobe -r moal;
 }
 
+# Issue in-band reset using sdio interface
+wifi_in_band_reset()
+{
+	if [ -f /proc/mwlan/adapter0/config ]; then
+		echo "fw_reload=1" > /proc/mwlan/adapter0/config
+	else
+		echo "Error: /proc/mwlan/adapter0/config does not exist."
+		exit 1
+	fi
+}
+
 ###########################
 #  Execution starts here  #
 ###########################
@@ -38,6 +49,9 @@ start)
 	;;
 stop)
 	wifi_stop
+	;;
+in-band-reset)
+	wifi_in_band_reset
 	;;
 esac
 
