imx8mp-var-dart: variscite-bt: wait for hci interface to come up
This avoids problems when rapidly stopping and starting variscite-bt

derived from commit b023192397ba0bc1e4ff7c52647403b769b68ace

Signed-off-by: Natalia Kovalenko <natasha.k@variscite.com>

diff --git a/recipes-connectivity/bcm43xx-utils/bcm43xx-utils/imx8mp-var-dart/variscite-bt b/recipes-connectivity/bcm43xx-utils/bcm43xx-utils/imx8mp-var-dart/variscite-bt
--- a/recipes-connectivity/bcm43xx-utils/bcm43xx-utils/imx8mp-var-dart/variscite-bt
+++ b/recipes-connectivity/bcm43xx-utils/bcm43xx-utils/imx8mp-var-dart/variscite-bt
@@ -154,6 +154,19 @@ bt_start_iw61x()
 	# Initialize and attach the BT device at 3000000
 	hciattach ${BT_TTY_DEV} any 3000000 flow
 
+	# Wait until the HCI interface comes up
+	if ! timeout 10 sh -c 'until hciconfig | grep -q "hci"; do sleep 0.1; done'; then
+		echo "Error: HCI interface did not come up"
+		exit 1
+	fi
+	# Wait until the Bluetooth MAC address is not 00:00:00:00:00:00
+	if ! timeout 10 sh -c 'until [ "$(hciconfig | grep "BD Address" | \
+	awk "{print \$3}")" != "00:00:00:00:00:00" ]; do sleep 0.1; done'; then
+		echo "Error: Bluetooth MAC address is 00:00:00:00:00:00"
+		exit 1
+	fi
+	sleep 1
+
 	# Fork a dummy process to satisfy the variscite-bt systemd service type=forking
 	(while true; do sleep 60; done) &
 }
